AllCops:
  TargetRubyVersion: 2.7

  Exclude:
    - 'appveyor.yml'
    - 'Vagrantfile'
    - 'scripts/**/*'
    - 'vendor/**/*'

Style/Encoding:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Metrics/BlockLength:
  Max: 200

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 250

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/FileName:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/AbcSize:
  Max: 26

